{
 "title": "Elad-Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_info, node)"
    }
   },
   {
    "name": "Instance",
    "query": {
     "query": "label_values(node_uname_info{nodename=\"$node\"}, instance)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{node=\"$node\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{job=\"kube-state-metrics\", node=\"$node\", namespace=\"$namespace\"}, pod)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(kube_pod_container_info{job=\"kube-state-metrics\", namespace=\"$namespace\", pod=\"$pod\"}, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number Of Pods in Nodes",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_pod_info{job=\"kube-state-metrics\", node=\"$node\"}) by (node)"
      }
     ]
    },
    {
     "title": "Cpu Used %",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\",instance=~\"$node\"}[5m])) * 100) "
      }
     ]
    },
    {
     "title": "Average Cpu Used By Cores",
     "type": "graph",
     "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "100 - avg(irate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\",cpu=\"0\",instance=\"$node\"}[5m])) *100 "
      },
      {
       "expr": "100 - avg(irate(node_cpu_seconds_total{job=\"node-exporter\",mode=\"idle\",cpu=\"1\",instance=\"$node\"}[5m])) *100 "
      }
     ]
    }
   ]
  },
  {
   "title": "NameSpace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod Restart In NameSpace",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}[1m])) by (namespace)"
      }
     ]
    },
    {
     "title": "Cpu Usage by NameSpace",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[5m])) by (namespace) * 100"
      }
     ]
    },
    {
     "title": "Number OF Deployment In NameSpace",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_deployment_created{namespace=\"$namespace\"}) by (namespace)"
      }
     ]
    },
    {
     "title": "Number Pods In NameSpace",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kube_pod_info{namespace=\"$namespace\"}) by (namespace)"
      }
     ]
    },
    {
     "title": "Network I/O receive/Transmit by Namespace ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\"}[5m])) by (namespace)"
      },
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\"}[5m])) by (namespace)"
      }
     ]
    },
    {
     "title": "Memory Use for NameSpace",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\"}) by (namespace)"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Age Pod",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - sum(kube_pod_created{pod=\"$pod\"})"
      }
     ]
    },
    {
     "title": "Cpu Used % By Pod",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{pod=\"$pod\", namespace=\"$namespace\"}[$__rate_interval])) by (pod) "
      }
     ]
    },
    {
     "title": "Ram Uage [AVG]",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(container_memory_usage_bytes{pod=\"$pod\"})"
      }
     ]
    },
    {
     "title": "CPU AVG",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(irate(container_cpu_usage_seconds_total{pod=\"$pod\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Disk I/O Read/Write",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{pod=\"$pod\"}[5m])) by (pod)"
      },
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{pod=\"$pod\"}[5m])) by (pod)"
      }
     ]
    },
    {
     "title": "Network Receive/Transmit For Pod",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{pod=\"$pod\"}[5m])) by (pod)"
      },
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{pod=~\"$pod\"}[5m])) by (pod)"
      }
     ]
    }
   ]
  },
  {
   "title": "Container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container  Usage CPU",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"$container\"}[$__rate_interval])) by (container) * 100"
      }
     ]
    },
    {
     "title": "Container Ram Usage ",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_memory_usage_bytes{container=\"$container\"}[$__rate_interval])) by (container)"
      }
     ]
    }
   ]
  }
 ]
}